### ISSUE TITLE
Self Hosted on Ubuntu

### ISSUE THREAD

**Issue by vwhissell** [Incognito/one-time-secret#74]
Trying to get the app working, self hosted

```
#cat run.sh
PUBLISH_SECRET_URI='/new' \
KEY_NAME_RANDOM_BYTES=128 \
PORT=80 \
DOMAIN=EXAMPLE.COM \
HTTP_TIMEOUT_MS=5000 \
MAX_UPLOAD_KB=128 \
node dist/bin/cli.js web:start
```

The web page works http://localhost/new , then I get this error when I click the Submit button.
I tried to play around with the DOMAIN variable, but I can't make it to work.

```
#./run.sh
{"message":"Starting webserver","level":"info"}
{"message":"Startint on port 80","level":"info"}
{"message":"Server Start listening on port 80","level":"info"}
/home/mis/Documents/one-time-secret/dist/src/WebControllers/ConfirmationController.js:30
                const secretUrl = new URL('/fetch', `https://${this.env.DOMAIN}`);
                                  ^

ReferenceError: URL is not defined
    at IncomingMessage.request.on (/home/user/Documents/one-time-secret/dist/src/WebControllers/ConfirmationController.js:30:35)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Incognito** [comment]
URL not being defined indicates the Node version is probably not configured to match the project. What version of node are you using (`node -v`)?

I set the engine config to 10.x ( https://github.com/Incognito/one-time-secret/blob/master/package.json#L8 )

The URL class became available globally in 10.x  https://nodejs.org/api/url.html#url_class_url

I advise using a more recent version of Node. While it is possible to introduce an import to make it available (`const { URL } = require('url');` or something along those lines) you'll also be going back several versions of security updates.

**Comment by Incognito** [comment]
You can find some instructions for installing Node 10 here:

https://github.com/nodesource/distributions/blob/master/README.md#deb

```
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by vwhissell** [comment]
Thanks. I was able to upgrade nodejs.
I have another problem :(

```
cat run.sh
PUBLISH_SECRET_URI='/publish' \
KEY_NAME_RANDOM_BYTES=256 \
PORT=80 \
DOMAIN=10.10.10.10 \
HTTP_TIMEOUT_MS=5000 \
MAX_UPLOAD_KB=1024 \
node dist/bin/cli.js web:start
```

The links that it creates are HTT{S, but the node server listens to HTTP only.

**Comment by vwhissell** [comment]
Oh, also

`I highly advise running a load balancer that does TLS (also called "SSL" or "HTTPS") in front of your app. Exposing secrets without encryption defeats the entire purpose. Certificates are free these days`

So, meanwhile, I will try to get an ngingx to "Proxy" https to the http nodejs server.

**Comment by Incognito** [comment]
> The links that it creates are HTT{S, but the node server listens to HTTP only.

This is by design.

https://github.com/Incognito/one-time-secret/blob/c3a5210f463ae7cd70fdb09d34ccc2d380c26efc/src/WebControllers/ConfirmationController.ts#L37

If the server communicated to a client over HTTP the web traffic would be in clear text (so there would be no reason for one-time-secrets or storing things  encrypted in memory).

Nginx would be used just to handle the certificates, it's far better at it and better supported than something I would put into the app. Nginx HTTPS and certificates is well tested, if I implemented one it would have very little testing.

You should be able to install nginx quite easily with something like http://www.nikola-breznjak.com/blog/javascript/nodejs/using-nginx-as-a-reverse-proxy-in-front-of-your-node-js-application/

And you can get free certificates via https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

**Comment by vwhissell** [comment]
thanks
